# This docker-compose file is intended for LOCAL development only
version: "3.4"

services:

  rules-enginee:
    build:
      context: .
      target: ${DOCKER_BUILD_TARGET}
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        SERVICE_NAME: channel-service
        SERVICE_HASH: ${SERVICE_HASH}
        SERVICE_PORT: 8007
        DYNATRACE_ENABLED: ${DYNATRACE_ENABLED}
        DEBUG_OPTS: ${DEBUG_OPTS}
    image: ${REGISTRY}/${REPOSITORY}/rules-enginee:${IMAGE_TAG}
    container_name: contacts-service
    environment:
      PROFILES_LABEL: native
    restart: unless-stopped
    ports:
      - "8007:8007"